package com.iflytek.renshou.pojo;

import java.util.ArrayList;
import java.util.List;

public class IatDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public IatDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOsIsNull() {
            addCriterion("os is null");
            return (Criteria) this;
        }

        public Criteria andOsIsNotNull() {
            addCriterion("os is not null");
            return (Criteria) this;
        }

        public Criteria andOsEqualTo(String value) {
            addCriterion("os =", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotEqualTo(String value) {
            addCriterion("os <>", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThan(String value) {
            addCriterion("os >", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThanOrEqualTo(String value) {
            addCriterion("os >=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThan(String value) {
            addCriterion("os <", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThanOrEqualTo(String value) {
            addCriterion("os <=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLike(String value) {
            addCriterion("os like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotLike(String value) {
            addCriterion("os not like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsIn(List<String> values) {
            addCriterion("os in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotIn(List<String> values) {
            addCriterion("os not in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsBetween(String value1, String value2) {
            addCriterion("os between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotBetween(String value1, String value2) {
            addCriterion("os not between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andNewdeployIsNull() {
            addCriterion("newDeploy is null");
            return (Criteria) this;
        }

        public Criteria andNewdeployIsNotNull() {
            addCriterion("newDeploy is not null");
            return (Criteria) this;
        }

        public Criteria andNewdeployEqualTo(String value) {
            addCriterion("newDeploy =", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployNotEqualTo(String value) {
            addCriterion("newDeploy <>", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployGreaterThan(String value) {
            addCriterion("newDeploy >", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployGreaterThanOrEqualTo(String value) {
            addCriterion("newDeploy >=", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployLessThan(String value) {
            addCriterion("newDeploy <", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployLessThanOrEqualTo(String value) {
            addCriterion("newDeploy <=", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployLike(String value) {
            addCriterion("newDeploy like", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployNotLike(String value) {
            addCriterion("newDeploy not like", value, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployIn(List<String> values) {
            addCriterion("newDeploy in", values, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployNotIn(List<String> values) {
            addCriterion("newDeploy not in", values, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployBetween(String value1, String value2) {
            addCriterion("newDeploy between", value1, value2, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andNewdeployNotBetween(String value1, String value2) {
            addCriterion("newDeploy not between", value1, value2, "newdeploy");
            return (Criteria) this;
        }

        public Criteria andEditionIsNull() {
            addCriterion("edition is null");
            return (Criteria) this;
        }

        public Criteria andEditionIsNotNull() {
            addCriterion("edition is not null");
            return (Criteria) this;
        }

        public Criteria andEditionEqualTo(String value) {
            addCriterion("edition =", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotEqualTo(String value) {
            addCriterion("edition <>", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionGreaterThan(String value) {
            addCriterion("edition >", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionGreaterThanOrEqualTo(String value) {
            addCriterion("edition >=", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLessThan(String value) {
            addCriterion("edition <", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLessThanOrEqualTo(String value) {
            addCriterion("edition <=", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionLike(String value) {
            addCriterion("edition like", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotLike(String value) {
            addCriterion("edition not like", value, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionIn(List<String> values) {
            addCriterion("edition in", values, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotIn(List<String> values) {
            addCriterion("edition not in", values, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionBetween(String value1, String value2) {
            addCriterion("edition between", value1, value2, "edition");
            return (Criteria) this;
        }

        public Criteria andEditionNotBetween(String value1, String value2) {
            addCriterion("edition not between", value1, value2, "edition");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(String value) {
            addCriterion("rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(String value) {
            addCriterion("rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(String value) {
            addCriterion("rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(String value) {
            addCriterion("rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(String value) {
            addCriterion("rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(String value) {
            addCriterion("rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLike(String value) {
            addCriterion("rate like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotLike(String value) {
            addCriterion("rate not like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<String> values) {
            addCriterion("rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<String> values) {
            addCriterion("rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(String value1, String value2) {
            addCriterion("rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(String value1, String value2) {
            addCriterion("rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andCaltypeIsNull() {
            addCriterion("calType is null");
            return (Criteria) this;
        }

        public Criteria andCaltypeIsNotNull() {
            addCriterion("calType is not null");
            return (Criteria) this;
        }

        public Criteria andCaltypeEqualTo(String value) {
            addCriterion("calType =", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeNotEqualTo(String value) {
            addCriterion("calType <>", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeGreaterThan(String value) {
            addCriterion("calType >", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeGreaterThanOrEqualTo(String value) {
            addCriterion("calType >=", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeLessThan(String value) {
            addCriterion("calType <", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeLessThanOrEqualTo(String value) {
            addCriterion("calType <=", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeLike(String value) {
            addCriterion("calType like", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeNotLike(String value) {
            addCriterion("calType not like", value, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeIn(List<String> values) {
            addCriterion("calType in", values, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeNotIn(List<String> values) {
            addCriterion("calType not in", values, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeBetween(String value1, String value2) {
            addCriterion("calType between", value1, value2, "caltype");
            return (Criteria) this;
        }

        public Criteria andCaltypeNotBetween(String value1, String value2) {
            addCriterion("calType not between", value1, value2, "caltype");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNull() {
            addCriterion("business is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNotNull() {
            addCriterion("business is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessEqualTo(String value) {
            addCriterion("business =", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotEqualTo(String value) {
            addCriterion("business <>", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThan(String value) {
            addCriterion("business >", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThanOrEqualTo(String value) {
            addCriterion("business >=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThan(String value) {
            addCriterion("business <", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThanOrEqualTo(String value) {
            addCriterion("business <=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLike(String value) {
            addCriterion("business like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotLike(String value) {
            addCriterion("business not like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessIn(List<String> values) {
            addCriterion("business in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotIn(List<String> values) {
            addCriterion("business not in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessBetween(String value1, String value2) {
            addCriterion("business between", value1, value2, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotBetween(String value1, String value2) {
            addCriterion("business not between", value1, value2, "business");
            return (Criteria) this;
        }

        public Criteria andComponentselectionIsNull() {
            addCriterion("componentSelection is null");
            return (Criteria) this;
        }

        public Criteria andComponentselectionIsNotNull() {
            addCriterion("componentSelection is not null");
            return (Criteria) this;
        }

        public Criteria andComponentselectionEqualTo(String value) {
            addCriterion("componentSelection =", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionNotEqualTo(String value) {
            addCriterion("componentSelection <>", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionGreaterThan(String value) {
            addCriterion("componentSelection >", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionGreaterThanOrEqualTo(String value) {
            addCriterion("componentSelection >=", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionLessThan(String value) {
            addCriterion("componentSelection <", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionLessThanOrEqualTo(String value) {
            addCriterion("componentSelection <=", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionLike(String value) {
            addCriterion("componentSelection like", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionNotLike(String value) {
            addCriterion("componentSelection not like", value, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionIn(List<String> values) {
            addCriterion("componentSelection in", values, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionNotIn(List<String> values) {
            addCriterion("componentSelection not in", values, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionBetween(String value1, String value2) {
            addCriterion("componentSelection between", value1, value2, "componentselection");
            return (Criteria) this;
        }

        public Criteria andComponentselectionNotBetween(String value1, String value2) {
            addCriterion("componentSelection not between", value1, value2, "componentselection");
            return (Criteria) this;
        }

        public Criteria andNoweditionIsNull() {
            addCriterion("nowEdition is null");
            return (Criteria) this;
        }

        public Criteria andNoweditionIsNotNull() {
            addCriterion("nowEdition is not null");
            return (Criteria) this;
        }

        public Criteria andNoweditionEqualTo(String value) {
            addCriterion("nowEdition =", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionNotEqualTo(String value) {
            addCriterion("nowEdition <>", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionGreaterThan(String value) {
            addCriterion("nowEdition >", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionGreaterThanOrEqualTo(String value) {
            addCriterion("nowEdition >=", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionLessThan(String value) {
            addCriterion("nowEdition <", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionLessThanOrEqualTo(String value) {
            addCriterion("nowEdition <=", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionLike(String value) {
            addCriterion("nowEdition like", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionNotLike(String value) {
            addCriterion("nowEdition not like", value, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionIn(List<String> values) {
            addCriterion("nowEdition in", values, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionNotIn(List<String> values) {
            addCriterion("nowEdition not in", values, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionBetween(String value1, String value2) {
            addCriterion("nowEdition between", value1, value2, "nowedition");
            return (Criteria) this;
        }

        public Criteria andNoweditionNotBetween(String value1, String value2) {
            addCriterion("nowEdition not between", value1, value2, "nowedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionIsNull() {
            addCriterion("upgradeEdition is null");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionIsNotNull() {
            addCriterion("upgradeEdition is not null");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionEqualTo(String value) {
            addCriterion("upgradeEdition =", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionNotEqualTo(String value) {
            addCriterion("upgradeEdition <>", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionGreaterThan(String value) {
            addCriterion("upgradeEdition >", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionGreaterThanOrEqualTo(String value) {
            addCriterion("upgradeEdition >=", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionLessThan(String value) {
            addCriterion("upgradeEdition <", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionLessThanOrEqualTo(String value) {
            addCriterion("upgradeEdition <=", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionLike(String value) {
            addCriterion("upgradeEdition like", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionNotLike(String value) {
            addCriterion("upgradeEdition not like", value, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionIn(List<String> values) {
            addCriterion("upgradeEdition in", values, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionNotIn(List<String> values) {
            addCriterion("upgradeEdition not in", values, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionBetween(String value1, String value2) {
            addCriterion("upgradeEdition between", value1, value2, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andUpgradeeditionNotBetween(String value1, String value2) {
            addCriterion("upgradeEdition not between", value1, value2, "upgradeedition");
            return (Criteria) this;
        }

        public Criteria andDeploytypeIsNull() {
            addCriterion("deployType is null");
            return (Criteria) this;
        }

        public Criteria andDeploytypeIsNotNull() {
            addCriterion("deployType is not null");
            return (Criteria) this;
        }

        public Criteria andDeploytypeEqualTo(String value) {
            addCriterion("deployType =", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeNotEqualTo(String value) {
            addCriterion("deployType <>", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeGreaterThan(String value) {
            addCriterion("deployType >", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeGreaterThanOrEqualTo(String value) {
            addCriterion("deployType >=", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeLessThan(String value) {
            addCriterion("deployType <", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeLessThanOrEqualTo(String value) {
            addCriterion("deployType <=", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeLike(String value) {
            addCriterion("deployType like", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeNotLike(String value) {
            addCriterion("deployType not like", value, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeIn(List<String> values) {
            addCriterion("deployType in", values, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeNotIn(List<String> values) {
            addCriterion("deployType not in", values, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeBetween(String value1, String value2) {
            addCriterion("deployType between", value1, value2, "deploytype");
            return (Criteria) this;
        }

        public Criteria andDeploytypeNotBetween(String value1, String value2) {
            addCriterion("deployType not between", value1, value2, "deploytype");
            return (Criteria) this;
        }

        public Criteria andYuyanIsNull() {
            addCriterion("yuYan is null");
            return (Criteria) this;
        }

        public Criteria andYuyanIsNotNull() {
            addCriterion("yuYan is not null");
            return (Criteria) this;
        }

        public Criteria andYuyanEqualTo(String value) {
            addCriterion("yuYan =", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanNotEqualTo(String value) {
            addCriterion("yuYan <>", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanGreaterThan(String value) {
            addCriterion("yuYan >", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanGreaterThanOrEqualTo(String value) {
            addCriterion("yuYan >=", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanLessThan(String value) {
            addCriterion("yuYan <", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanLessThanOrEqualTo(String value) {
            addCriterion("yuYan <=", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanLike(String value) {
            addCriterion("yuYan like", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanNotLike(String value) {
            addCriterion("yuYan not like", value, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanIn(List<String> values) {
            addCriterion("yuYan in", values, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanNotIn(List<String> values) {
            addCriterion("yuYan not in", values, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanBetween(String value1, String value2) {
            addCriterion("yuYan between", value1, value2, "yuyan");
            return (Criteria) this;
        }

        public Criteria andYuyanNotBetween(String value1, String value2) {
            addCriterion("yuYan not between", value1, value2, "yuyan");
            return (Criteria) this;
        }

        public Criteria andShougongIsNull() {
            addCriterion("shouGong is null");
            return (Criteria) this;
        }

        public Criteria andShougongIsNotNull() {
            addCriterion("shouGong is not null");
            return (Criteria) this;
        }

        public Criteria andShougongEqualTo(String value) {
            addCriterion("shouGong =", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongNotEqualTo(String value) {
            addCriterion("shouGong <>", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongGreaterThan(String value) {
            addCriterion("shouGong >", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongGreaterThanOrEqualTo(String value) {
            addCriterion("shouGong >=", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongLessThan(String value) {
            addCriterion("shouGong <", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongLessThanOrEqualTo(String value) {
            addCriterion("shouGong <=", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongLike(String value) {
            addCriterion("shouGong like", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongNotLike(String value) {
            addCriterion("shouGong not like", value, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongIn(List<String> values) {
            addCriterion("shouGong in", values, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongNotIn(List<String> values) {
            addCriterion("shouGong not in", values, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongBetween(String value1, String value2) {
            addCriterion("shouGong between", value1, value2, "shougong");
            return (Criteria) this;
        }

        public Criteria andShougongNotBetween(String value1, String value2) {
            addCriterion("shouGong not between", value1, value2, "shougong");
            return (Criteria) this;
        }

        public Criteria andExplainIsNull() {
            addCriterion("explain is null");
            return (Criteria) this;
        }

        public Criteria andExplainIsNotNull() {
            addCriterion("explain is not null");
            return (Criteria) this;
        }

        public Criteria andExplainEqualTo(String value) {
            addCriterion("explain =", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotEqualTo(String value) {
            addCriterion("explain <>", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainGreaterThan(String value) {
            addCriterion("explain >", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainGreaterThanOrEqualTo(String value) {
            addCriterion("explain >=", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLessThan(String value) {
            addCriterion("explain <", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLessThanOrEqualTo(String value) {
            addCriterion("explain <=", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLike(String value) {
            addCriterion("explain like", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotLike(String value) {
            addCriterion("explain not like", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainIn(List<String> values) {
            addCriterion("explain in", values, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotIn(List<String> values) {
            addCriterion("explain not in", values, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainBetween(String value1, String value2) {
            addCriterion("explain between", value1, value2, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotBetween(String value1, String value2) {
            addCriterion("explain not between", value1, value2, "explain");
            return (Criteria) this;
        }

        public Criteria andExtend1IsNull() {
            addCriterion("extend1 is null");
            return (Criteria) this;
        }

        public Criteria andExtend1IsNotNull() {
            addCriterion("extend1 is not null");
            return (Criteria) this;
        }

        public Criteria andExtend1EqualTo(String value) {
            addCriterion("extend1 =", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1NotEqualTo(String value) {
            addCriterion("extend1 <>", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1GreaterThan(String value) {
            addCriterion("extend1 >", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1GreaterThanOrEqualTo(String value) {
            addCriterion("extend1 >=", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1LessThan(String value) {
            addCriterion("extend1 <", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1LessThanOrEqualTo(String value) {
            addCriterion("extend1 <=", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1Like(String value) {
            addCriterion("extend1 like", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1NotLike(String value) {
            addCriterion("extend1 not like", value, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1In(List<String> values) {
            addCriterion("extend1 in", values, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1NotIn(List<String> values) {
            addCriterion("extend1 not in", values, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1Between(String value1, String value2) {
            addCriterion("extend1 between", value1, value2, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend1NotBetween(String value1, String value2) {
            addCriterion("extend1 not between", value1, value2, "extend1");
            return (Criteria) this;
        }

        public Criteria andExtend2IsNull() {
            addCriterion("extend2 is null");
            return (Criteria) this;
        }

        public Criteria andExtend2IsNotNull() {
            addCriterion("extend2 is not null");
            return (Criteria) this;
        }

        public Criteria andExtend2EqualTo(String value) {
            addCriterion("extend2 =", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2NotEqualTo(String value) {
            addCriterion("extend2 <>", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2GreaterThan(String value) {
            addCriterion("extend2 >", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2GreaterThanOrEqualTo(String value) {
            addCriterion("extend2 >=", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2LessThan(String value) {
            addCriterion("extend2 <", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2LessThanOrEqualTo(String value) {
            addCriterion("extend2 <=", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2Like(String value) {
            addCriterion("extend2 like", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2NotLike(String value) {
            addCriterion("extend2 not like", value, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2In(List<String> values) {
            addCriterion("extend2 in", values, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2NotIn(List<String> values) {
            addCriterion("extend2 not in", values, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2Between(String value1, String value2) {
            addCriterion("extend2 between", value1, value2, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend2NotBetween(String value1, String value2) {
            addCriterion("extend2 not between", value1, value2, "extend2");
            return (Criteria) this;
        }

        public Criteria andExtend3IsNull() {
            addCriterion("extend3 is null");
            return (Criteria) this;
        }

        public Criteria andExtend3IsNotNull() {
            addCriterion("extend3 is not null");
            return (Criteria) this;
        }

        public Criteria andExtend3EqualTo(String value) {
            addCriterion("extend3 =", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3NotEqualTo(String value) {
            addCriterion("extend3 <>", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3GreaterThan(String value) {
            addCriterion("extend3 >", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3GreaterThanOrEqualTo(String value) {
            addCriterion("extend3 >=", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3LessThan(String value) {
            addCriterion("extend3 <", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3LessThanOrEqualTo(String value) {
            addCriterion("extend3 <=", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3Like(String value) {
            addCriterion("extend3 like", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3NotLike(String value) {
            addCriterion("extend3 not like", value, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3In(List<String> values) {
            addCriterion("extend3 in", values, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3NotIn(List<String> values) {
            addCriterion("extend3 not in", values, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3Between(String value1, String value2) {
            addCriterion("extend3 between", value1, value2, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend3NotBetween(String value1, String value2) {
            addCriterion("extend3 not between", value1, value2, "extend3");
            return (Criteria) this;
        }

        public Criteria andExtend4IsNull() {
            addCriterion("extend4 is null");
            return (Criteria) this;
        }

        public Criteria andExtend4IsNotNull() {
            addCriterion("extend4 is not null");
            return (Criteria) this;
        }

        public Criteria andExtend4EqualTo(String value) {
            addCriterion("extend4 =", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4NotEqualTo(String value) {
            addCriterion("extend4 <>", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4GreaterThan(String value) {
            addCriterion("extend4 >", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4GreaterThanOrEqualTo(String value) {
            addCriterion("extend4 >=", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4LessThan(String value) {
            addCriterion("extend4 <", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4LessThanOrEqualTo(String value) {
            addCriterion("extend4 <=", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4Like(String value) {
            addCriterion("extend4 like", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4NotLike(String value) {
            addCriterion("extend4 not like", value, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4In(List<String> values) {
            addCriterion("extend4 in", values, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4NotIn(List<String> values) {
            addCriterion("extend4 not in", values, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4Between(String value1, String value2) {
            addCriterion("extend4 between", value1, value2, "extend4");
            return (Criteria) this;
        }

        public Criteria andExtend4NotBetween(String value1, String value2) {
            addCriterion("extend4 not between", value1, value2, "extend4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iat_data
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 27 00:01:18 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}