package com.iflytek.renshou.pojo;

public class IsmData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.id
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.os
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.newDeploy
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String newdeploy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.edition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String edition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.rate
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.calType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String caltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.business
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.componentSelection
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String componentselection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.nowEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String nowedition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.upgradeEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String upgradeedition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.deployType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String deploytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.yuYan
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String yuyan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.shouGong
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String shougong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.explain
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String explain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.extend1
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String extend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.extend2
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String extend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.extend3
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String extend3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ism_data.extend4
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    private String extend4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.id
     *
     * @return the value of ism_data.id
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.id
     *
     * @param id the value for ism_data.id
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.os
     *
     * @return the value of ism_data.os
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.os
     *
     * @param os the value for ism_data.os
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.newDeploy
     *
     * @return the value of ism_data.newDeploy
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getNewdeploy() {
        return newdeploy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.newDeploy
     *
     * @param newdeploy the value for ism_data.newDeploy
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setNewdeploy(String newdeploy) {
        this.newdeploy = newdeploy == null ? null : newdeploy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.edition
     *
     * @return the value of ism_data.edition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.edition
     *
     * @param edition the value for ism_data.edition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setEdition(String edition) {
        this.edition = edition == null ? null : edition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.rate
     *
     * @return the value of ism_data.rate
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.rate
     *
     * @param rate the value for ism_data.rate
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.calType
     *
     * @return the value of ism_data.calType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getCaltype() {
        return caltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.calType
     *
     * @param caltype the value for ism_data.calType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setCaltype(String caltype) {
        this.caltype = caltype == null ? null : caltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.business
     *
     * @return the value of ism_data.business
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.business
     *
     * @param business the value for ism_data.business
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.componentSelection
     *
     * @return the value of ism_data.componentSelection
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getComponentselection() {
        return componentselection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.componentSelection
     *
     * @param componentselection the value for ism_data.componentSelection
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setComponentselection(String componentselection) {
        this.componentselection = componentselection == null ? null : componentselection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.nowEdition
     *
     * @return the value of ism_data.nowEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getNowedition() {
        return nowedition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.nowEdition
     *
     * @param nowedition the value for ism_data.nowEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setNowedition(String nowedition) {
        this.nowedition = nowedition == null ? null : nowedition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.upgradeEdition
     *
     * @return the value of ism_data.upgradeEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getUpgradeedition() {
        return upgradeedition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.upgradeEdition
     *
     * @param upgradeedition the value for ism_data.upgradeEdition
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setUpgradeedition(String upgradeedition) {
        this.upgradeedition = upgradeedition == null ? null : upgradeedition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.deployType
     *
     * @return the value of ism_data.deployType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getDeploytype() {
        return deploytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.deployType
     *
     * @param deploytype the value for ism_data.deployType
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setDeploytype(String deploytype) {
        this.deploytype = deploytype == null ? null : deploytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.yuYan
     *
     * @return the value of ism_data.yuYan
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getYuyan() {
        return yuyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.yuYan
     *
     * @param yuyan the value for ism_data.yuYan
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setYuyan(String yuyan) {
        this.yuyan = yuyan == null ? null : yuyan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.shouGong
     *
     * @return the value of ism_data.shouGong
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getShougong() {
        return shougong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.shouGong
     *
     * @param shougong the value for ism_data.shouGong
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setShougong(String shougong) {
        this.shougong = shougong == null ? null : shougong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.explain
     *
     * @return the value of ism_data.explain
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.explain
     *
     * @param explain the value for ism_data.explain
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.extend1
     *
     * @return the value of ism_data.extend1
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.extend1
     *
     * @param extend1 the value for ism_data.extend1
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.extend2
     *
     * @return the value of ism_data.extend2
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.extend2
     *
     * @param extend2 the value for ism_data.extend2
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.extend3
     *
     * @return the value of ism_data.extend3
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.extend3
     *
     * @param extend3 the value for ism_data.extend3
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ism_data.extend4
     *
     * @return the value of ism_data.extend4
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ism_data.extend4
     *
     * @param extend4 the value for ism_data.extend4
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }
}