package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.IatData;
import com.iflytek.renshou.pojo.IatDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IatDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(IatDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(IatDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(IatData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(IatData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<IatData> selectByExample(IatDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    IatData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") IatData record, @Param("example") IatDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") IatData record, @Param("example") IatDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(IatData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iat_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(IatData record);
}