package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.ImsAiData;
import com.iflytek.renshou.pojo.ImsAiDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImsAiDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(ImsAiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(ImsAiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(ImsAiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(ImsAiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<ImsAiData> selectByExample(ImsAiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    ImsAiData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImsAiData record, @Param("example") ImsAiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") ImsAiData record, @Param("example") ImsAiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(ImsAiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_ai_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(ImsAiData record);
}