package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.ImsTtsData;
import com.iflytek.renshou.pojo.ImsTtsDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImsTtsDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(ImsTtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(ImsTtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(ImsTtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(ImsTtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<ImsTtsData> selectByExample(ImsTtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    ImsTtsData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImsTtsData record, @Param("example") ImsTtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") ImsTtsData record, @Param("example") ImsTtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(ImsTtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ims_tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(ImsTtsData record);
}