package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.IsmData;
import com.iflytek.renshou.pojo.IsmDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IsmDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(IsmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(IsmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(IsmData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(IsmData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<IsmData> selectByExample(IsmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    IsmData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") IsmData record, @Param("example") IsmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") IsmData record, @Param("example") IsmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(IsmData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ism_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(IsmData record);
}