package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.JianXiData;
import com.iflytek.renshou.pojo.JianXiDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JianXiDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(JianXiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(JianXiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(JianXiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(JianXiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<JianXiData> selectByExample(JianXiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    JianXiData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") JianXiData record, @Param("example") JianXiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") JianXiData record, @Param("example") JianXiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(JianXiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianxi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(JianXiData record);
}