package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.TtsData;
import com.iflytek.renshou.pojo.TtsDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtsDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(TtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(TtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(TtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(TtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<TtsData> selectByExample(TtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    TtsData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TtsData record, @Param("example") TtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") TtsData record, @Param("example") TtsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(TtsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tts_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(TtsData record);
}