package com.iflytek.renshou.dao;

import com.iflytek.renshou.pojo.YanZhiData;
import com.iflytek.renshou.pojo.YanZhiDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YanZhiDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int countByExample(YanZhiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByExample(YanZhiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insert(YanZhiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int insertSelective(YanZhiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    List<YanZhiData> selectByExample(YanZhiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    YanZhiData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") YanZhiData record, @Param("example") YanZhiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByExample(@Param("record") YanZhiData record, @Param("example") YanZhiDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKeySelective(YanZhiData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanzhi_data
     *
     * @mbggenerated Fri Mar 27 00:01:18 CST 2020
     */
    int updateByPrimaryKey(YanZhiData record);
}